package com.company;

public enum State {
    NUMBER, NUMBER_DECIMAL, //0-9 .
    START,
    ERROR,
    PRE_EQUAL_OPERATOR, //= % ! + - < >
    PRE_NUMBER_OPERATOR, // - +
    DOT, // .
    IDENTIFIER,
    COMMENT, // /
    MULTILINE_COMMENT,
    SINGLELINE_COMMENT,
    MULTILINE_COMMENT_STAR,
    OPER_FIRST_SYM,
    STRING_LITERAL, STRING_LITERAL_SYMBOL, STRING_LITERAL_BODY
}
